### ISSUE TITLE
Finding intersections where the temperature line in soundings and parcel lines cross

### ISSUE THREAD

**Issue by github0013** [chird/meteoJS#49]
First of all, thank you for this great library.   I have searched for Skew-T diagram libraries so much and yet never seen any others well developed like yours.

After adding a parcel lines, you will see something like these, right?

<img width="337" alt="b" src="https://user-images.githubusercontent.com/809378/112070737-aa71f780-8bb1-11eb-86c8-0119bcc29521.png">
<img width="425" alt="a" src="https://user-images.githubusercontent.com/809378/112070742-ac3bbb00-8bb1-11eb-867d-5c145e2b0f0e.png">

What I want to find is a way to get the altitude (get the pressure and also temperature [if can]) at these points where the lines intersect.

I think, to get an altitude, [I just need a pressure value][1].    I looked over `Sounding`, `DiagramSounding`, `DiagramParcel` and `TDDiagram` classes but I don't think it doesn't yet support getting the intersections I am looking for.

Do you think it's possible to calculate these points out?

[1]: https://github.com/chird/meteoJS/blob/v1.14.0/src/meteoJS/calc.js#L17

**Comment by chird** [comment]
Hi, thank you for your compliment and feedback. The library isn't yet perfect. In the second picture there is a floating point precision issue visible for the dark orange line. :(

There's (yet) no method to calculate the intersections. But the algorithm would be something like that (untested):

```
const thetak = potentialTempByTempAndPres(tempCelsiusToKelvin(parcel.tmpc), parcel.pres);
const hmr = saturationHMRByTempAndPres(tempCelsiusToKelvin(parcel.dwpc), parcel.pres);
const lclpres = lclByPotentialTempAndHMR(pottmpk, hmr);
const lcltmpk = lclTemperatureByTempAndDewpoint(tempCelsiusToKelvin(parcel.tmpc), tempCelsiusToKelvin(parcel.dwpc));
const thetaek = equiPotentialTempByTempAndDewpointAndPres(lcltmpk, lcltmpk, lclpres);

const intersectinPoints = [];
let lastLevelData = undefined;
sounding.getLevels().forEach(levelData => {
  if (lastLevelData === undefined) {
    lastLevelData = levelData;
    return;
  }
  if (levelData.pres <= lclpres) {
    const theta1 = potentialTempByTempAndPres(tempCelsiusToKelvin(lastLevelData.tmpc), lastLevelData.pres);
    const theta2 = potentialTempByTempAndPres(tempCelsiusToKelvin(levelData.tmpc), levelData.pres);
    // Check side of both point
    const sign1 = Math.sign(theta1 - thetak);
    const sign2 = Math.sign(theta2 - thetak);
    if (sign1 != sign2)
      return;
    const presIntersection = a * thetak + b;
    intersectinPoints.push([thetak, presIntersection]);
  }
  else {
    // the same with the equivalent potential temperature
  }
  lastLevelData = levelData;
});
```

_Remark 1:_
The algorithm (inspired by https://stackoverflow.com/a/385873) is performed in the Pressure-Theta plane respectively Pressure-ThetaE plane. This is not exactly the same as what you see in the thermodynamic diagram. But the differences will be small, I think.
_Remark 2:_
The lower marked point in your second image is the intersection between the mixing ratio and the temperature. This is not covered by the code above.

Cheers, Ivo

**Comment by github0013** [comment]
Thank you for your sample code.   Because I haven't studied any bits of meteorology, I really don't know what's going on.   But I am guessing you are sort of like plotting potential temperature as x value and pressure as y value at each level in sounding data, then compare continuous 2 points (theta1, theta2) with parcel potential temperature.

```js
const thetak = potentialTempByTempAndPres(
  tempCelsiusToKelvin(parcel.tmpc),
  parcel.pres
);
const hmr = saturationHMRByTempAndPres(
  tempCelsiusToKelvin(parcel.dwpc),
  parcel.pres
);
const lclpres = lclByPotentialTempAndHMR(pottmpk, hmr);  // pottmpk is not defined.  is it maybe thetak?
const lcltmpk = lclTemperatureByTempAndDewpoint(
  tempCelsiusToKelvin(parcel.tmpc),
  tempCelsiusToKelvin(parcel.dwpc)
);
const thetaek = equiPotentialTempByTempAndDewpointAndPres(
  lcltmpk,
  lcltmpk,
  lclpres
);

const intersectinPoints = [];
let lastLevelData = undefined;
sounding.getLevels().forEach((levelData) => {  // sounding.getLevels() returns pressure levels such as 1000, 925, 900 ...
  if (lastLevelData === undefined) {
    lastLevelData = levelData;
    return;
  }
  if (levelData.pres <= lclpres) {
    const theta1 = potentialTempByTempAndPres(
      tempCelsiusToKelvin(lastLevelData.tmpc),
      lastLevelData.pres
    );
    const theta2 = potentialTempByTempAndPres(
      tempCelsiusToKelvin(levelData.tmpc),
      levelData.pres
    );
    // Check side of both point
    const sign1 = Math.sign(theta1 - thetak);
    const sign2 = Math.sign(theta2 - thetak);
    if (sign1 != sign2) return;
    const a = (lastLevelData.pres - levelData.pres) / (theta1 - theta2);
    const b = a * theta2 + levelData.pres;
    const presIntersection = a * thetak + b;
    intersectinPoints.push([thetak, presIntersection]);
  } else {
    // the same with the equivalent potential temperature
  }
  lastLevelData = levelData;
});
```

Perhaps `levelData` can be retrieved like this?

```js
sounding.getLevels().forEach((level) => {
  const levelData = sounding.getData(level)
  ...
```

If so, `levelData` contains `tmpk` instead of `tmpc`.  So then, theta1 and 2 will be like this?

```js
const theta1 = meteoJS.calc.potentialTempByTempAndPres(
  lastLevelData.tmpk,
  lastLevelData.pres
)
const theta2 = meteoJS.calc.potentialTempByTempAndPres(
  levelData.tmpk,
  levelData.pres
)
```

I think you are checking if the environmental temperature is crossing over the dry adiabatic lapse rate line?
```js
const sign1 = Math.sign(theta1 - thetak);
const sign2 = Math.sign(theta2 - thetak);
if (sign1 != sign2) return;
```


After reading your [stackoverflow link][1], I guess you are performing [intersection of 2 lines][2]?
Are you performing the math here?
```js
const a = (lastLevelData.pres - levelData.pres) / (theta1 - theta2);
const b = a * theta2 + levelData.pres;
const presIntersection = a * thetak + b;
```

<img width="635" alt="Notification_Center-2" src="https://user-images.githubusercontent.com/809378/112257121-af18d780-8ca7-11eb-818f-2385db2132c5.png">


The both of moist adiabatic lapse rate and dry adiabatic lapse rate line are, I guess you can say they are linear.   So I was first thinking you were drawing a line from the parcel begin point  (the "dry") to LCL and were checking if the line gets crossed with environmental temperature line (`levelData` and `lastLevelData`), but I am not sure that's what you did in the code.

Plus, I am not sure the reason why you separate the higher altitude above LCL? (is it for wet adiabatic lapse rate line?)

Can you kindly explain a bit more when you have time?

[1]: https://stackoverflow.com/questions/385305/efficient-maths-algorithm-to-calculate-intersections/385873#385873
[2]: https://keisan.casio.com/exec/system/1223519249

**Comment by chird** [comment]
> Perhaps levelData can be retrieved like this?

Your right. There's a bug in the documentation.

> If so, levelData contains tmpk instead of tmpc. So then, theta1 and 2 will be like this?

Yes. Correct.

**Comment by chird** [comment]
A parcel lift starts at a certain level (pressure). A parcel is fully defined by this level and its temperature and humidity at this level. In your picture above, the temperature is at the circle labelled "dry". And the humidity can be defined by the dew point temperature (labelled "moist"). The air parcel is lifted up to the LCL (lifting condensation level). This is a dry adiabatic process. This means the potential temperature (Symbol usually a greek Theta) and the mixing ratio is constant. So the line starting at the point "dry" follows the dry adiabats, the line starting at the point "moist" follows the constant mixing ratio lines. They meet at the LCL. Above the LCL latent heat will be released (formation of clouds and probably rain). Here the Equivalent potential temperature is constant (Symbol usually a greek Theta with an subscript "e").

Hence, the intersections below the LCL can be found via the potential temperature, above the LCL via the equivalent potential temperature.

> But I am guessing you are sort of like plotting potential temperature as x value and pressure as y value at each level in sounding data, then compare continuous 2 points (theta1, theta2) with parcel potential temperature.

Correct.

> I think you are checking if the environmental temperature is crossing over the dry adiabatic lapse rate line?

Exactly.

> Are you performing the math here?

Yes. "a" and "b" are the slope/intercept of the linear equation in the pressure-potential temperature plane.

> The both of moist adiabatic lapse rate and dry adiabatic lapse rate line are, I guess you can say they are linear.

You mixed up something. See my explanations above. The moist adiabatic lapse rate behaves to the part above the LCL.

> Plus, I am not sure the reason why you separate the higher altitude above LCL?

See my explanations above. Because above the LCL the equivalent potential temperature is constant. So above the LCL we can find the interceptions via this.
