### ISSUE TITLE
Is there a way to change wind speed unit in m/s in the wind speed profile?

### ISSUE THREAD

**Issue by github0013** [chird/meteoJS#60]
<img width="182" alt="Screen Shot 2022-06-09 at 9 49 31" src="https://user-images.githubusercontent.com/809378/172741182-6554dc32-9cd4-4a7a-b026-2086aa6288ce.png">

```js
const diagram = new meteoJS.ThermodynamicDiagram({
  renderTo,
  windspeedProfileAxis: {
    labels: {
      unit: "m/s",
      prefix: "m/s",
    },
  },
})
```

I could change windspeed x-axis label unit in m/s like that above.  However, it seems not possible to change the windspeed unit on hover?

https://github.com/chird/meteoJS/blob/0a76e1eb720a88e193a6942ac68a3ddfc8805ada/src/meteoJS/thermodynamicDiagram/WindspeedProfile.js#L296

Is this the part showing the hover text?  hard coded in knot?

**Comment by chird** [comment]
Yes, it is hardcoded (yet).

But theirs an [option](https://chird.github.io/meteoJS/doc/module-meteoJS_thermodynamicDiagram_plotDataArea.html#~insertLabelsFunc) to override the full function, which draws the hover label.

```js
const diagram = new meteoJS.ThermodynamicDiagram({
  renderTo,
  windspeedProfile: {
    hoverLabels: {
      insertLabelsFunc: (sounding, levelData, group) => {
        …
      }
    },
  },
})
```

You could basically copy this function (but have to replace `this`):

https://github.com/chird/meteoJS/blob/0a76e1eb720a88e193a6942ac68a3ddfc8805ada/src/meteoJS/thermodynamicDiagram/WindspeedProfile.js#L253..L304

And then you could change your highlighted line to something like that:

```js
`${Math.round(levelData.wspd*10)/10} m/s`
```

**Comment by chird** [comment]
A first brief answer: I try to prepare a release 1.16.2 soon. With this release the unit will be configurable.

**Comment by chird** [comment]
I just released 1.17.0 with the new options. Now you can do something like this:

```js
const diagram = new meteoJS.ThermodynamicDiagram({
  renderTo,
  windspeedProfile: {
    hoverLabels: {
      windspeed: {
        windspeed: {
          unit: 'm/s',
          decimalPlaces: 1,
          prefix: ' m/s'
        }
      }
    }
  }
});
```

**Comment by github0013** [comment]
It feels like to me, if it was `suffix` instead of `prefix`, it sounds more intuitive.

**Comment by chird** [comment]
Oh, of course. Thank you for the hint. I have adopted the options without thinking about it so far. It was already incorrect before. I will introduce the suffix option in the next release, backwards compatible of course.
