### ISSUE TITLE
i need to update sounding elements instead of owveriting  diagram with new one 

### ISSUE THREAD

**Issue by hadjersh97** [chird/meteoJS#61]
Hi,   
i'm using TermodynamicDiagram-default example and i'm trying to play with it in React.
my task is to change colors of diagram/hodogram/winds and make them visible/invisible.
i want to access to a specific sounding by id and update it without generating each time a new TermodynamicDiagram . 
 my question is : 
   Is there methods that update differents elements of sounding such as wind/hodograph/.. ?

**Comment by chird** [comment]
Ouh, it's a bug. The `visible` property is currently ignored.

As a work-around, you could set the `width` to `0` (within `style`).

**Comment by hadjersh97** [comment]
alright, Thanks for help
