### ISSUE TITLE
add only one horizontal line (isobar) inside thermodynamicDiagram and move it by mouse 

### ISSUE THREAD

**Issue by hadjersh97** [chird/meteoJS#62]
Hi, 
     i'm asking to create a straight line above ThermodinamicDiagram at any position and move it with mouse , i tried to make it inside the div but  sometimes my line stopped when i click on some elements inside the diagram that fire the event mouseEvent .

Qs :  is there a way or method that draw a line (one isobar) and let the possibility to move it ?

**Comment by chird** [comment]
Hi,
there's an API option. You can do something like that:

```js
td =  new ThermodynamicDiagram({
  'diagram': {
    'hoverLabels': {
      'pres': {
        'length': '100%'
      }
    }
  }
});
```

This will add a horizontal isobar line moving with the mouse. It is combined with the hover label for the pressure level. (for details see [API](https://chird.github.io/meteoJS/doc/module-meteoJS_thermodynamicDiagram_tdDiagram.html#~presLabelOptions))

**Comment by hadjersh97** [comment]
yes true, it's working , i will read about it  more.
Thank you so much.
