### ISSUE TITLE
add only one isotherm line inside thermodynamicDiagram and move it by mouse 

### ISSUE THREAD

**Issue by hadjersh97** [chird/meteoJS#63]
Hi  Chird ,
 i should make isotherms one isotherm moved by hovering.  

please, is that possible by this library?. otherwise what you suppose?

Thanks soooo much for help many times

**Comment by chird** [comment]
Hi hadjersh97,

You have to code it yourself. Via the `diagram` property, you have access to the thermodynamic diagram. And then via the `svgNode` property access to its SVG. I suggest to create a new group. This way you can add and remove lines in the SVG without modifying the other parts.

The [diagram](https://chird.github.io/meteoJS/doc/module-meteoJS_thermodynamicDiagram_tdDiagram.TDDiagram.html) fires a [mouse move event](https://chird.github.io/meteoJS/doc/module-meteoJS_thermodynamicDiagram_tdDiagram.html#event:mousemove). It passes the pressure and air temperature at the position of the mouse pointer.

Futhermore with the `coordinateSystem` property, you can access the coordinate system and its conversion functions. The [getXByYT(y, T)](https://chird.github.io/meteoJS/doc/module-meteoJS_thermodynamicDiagram_coordinateSystem.CoordinateSystem.html#getXByYT) and the [getYByXT(x, T)](https://chird.github.io/meteoJS/doc/module-meteoJS_thermodynamicDiagram_coordinateSystem.CoordinateSystem.html#getYByXT) should do the further work if the isotherms are straight lines. (see the [API docs](https://chird.github.io/meteoJS/doc/module-meteoJS_thermodynamicDiagram_coordinateSystem.CoordinateSystem.html))

I haven't tested the following code. But I would start with something like this:
```js
const diagram = new ThermodynamicDiagram({
  renderTo
});
const group = diagram.diagram.svg.group();
const tdDiagram = diagram.diagram;
tdDiagram.on('mousemove', (p, T) => {
  group.clear();

  const y0 = tdDiagram.getYByXT(0, T);
  const y1 = tdDiagram.getYByXT(tdDiagram.width, T);
  const x0 = tdDiagram.getXByYT(0, T);
  const x1 = tdDiagram.getXByYT(tdDiagram.height, T);
  
  // and then draw a SVG-line in "group" from (x0,y0) to (x1,y1)
});
```

I hope this helps. Cheers.

**Comment by hadjersh97** [comment]
Hi Chird,
Thanks for the proposition, actually that what i was doing. 
i have tried your suggestion , inside mousemove function i did :
1- i  have tested if the new group doesn't exist before, otherwise i remove it.
2- i  have created the new  group.
3- then ,i created the new line with the coordinations that you gived in the answer , but T (parametere ) shows error is not defined then i replaced T by p.diagramTmpk.
```tdTermo.diagram.on("mousemove", (p) => {
....
            let T = p.diagramTmpk;
            const y0 = tdDiagram.coordinateSystem.getYByXT(0, T);
            const y1 = tdDiagram.coordinateSystem.getYByXT(tdDiagram.width, T);
            const x0 = tdDiagram.coordinateSystem.getXByYT(0, T);
            const x1 = tdDiagram.coordinateSystem.getXByYT(tdDiagram.height, T);
.....
```
4- i append the new line to the new group then the i appended th e new group to `tdTermo.diagram.svgGroups.isotherms.node`     

the issue now the lines **are not in same parallelism as isotherms**, they start from **the up left to the down right**
so i guess the problem with coordination

**Comment by chird** [comment]
Hi hadjersh97,

I just wanted to know myself, how I have to implement it. Here is my tested code:

```js
  const diagram = new meteoJS.ThermodynamicDiagram({
    renderTo
  });
  const tdDiagram = diagram.diagram;
  const hoverIsothermGroup = tdDiagram.svgNode.group();
  tdDiagram.on('mousemove', ({ diagramTmpk }) => {
    hoverIsothermGroup.clear();

    const y0 = tdDiagram.coordinateSystem.getYByXT(0, diagramTmpk);
    const y1 = tdDiagram.coordinateSystem.getYByXT(tdDiagram.width, diagramTmpk);

    hoverIsothermGroup.line(0, tdDiagram.height - y0, tdDiagram.width, tdDiagram.height - y1).stroke({ width: 1, color: 'red' });
  });
```

The misalignment stems from the inverse y axis between my coordinate system and the SVG coordinates. And, of course, the line must extend from left to right.

Probably, the animation would be smoother if you just move the line instead of redrawing it. And with my code, parts of the line are hidden. Specifically, the parts below and above the diagram. This could also be better solved in the code.

**Comment by hadjersh97** [comment]
![isotherm](https://user-images.githubusercontent.com/75619237/175649892-077edcff-0464-48c9-90b5-fba078c49f30.png)

hi again Chird,
 as u see in the picture the new drawn line is represented with the red one , and i tried your previous coordination , and i want something same paralelisme like the black line. 

for the animaton yes, it would be better as u said if i just move the line instead of hoveing over the diagram. like isobar. i guess this need another solution.

**Comment by chird** [comment]
Could you post your code? Its strange because my code worked correctly.

Moving the line shouldn't be too complicated. I use this library: https://svgjs.dev/docs/3.0/ I think the "manipulating" chapter will give the solution.

**Comment by hadjersh97** [comment]
yes sure here is my code 
```
 const plotIsotherms = (tdTermo) => { 
      const tdGroup = tdTermo.diagram.svgGroups.isotherms.node;
      var newGroup;
      const tdDiagram = tdTermo.diagram;
      tdTermo.diagram.on("mousemove", (p) => {
        const element = document.querySelector('#new');
        if( typeof(element)!= undefined &&  element!= null) {
          newGroup.remove();
         }
          else {
            newGroup = document.createElementNS('http://www.w3.org/2000/svg','g');
            newGroup.setAttribute("id",'new');
            var newLine = document.createElementNS('http://www.w3.org/2000/svg','line');
            let T = p.diagramTmpk;
            const y0 = tdDiagram.coordinateSystem.getYByXT(0, T);
            const y1 = tdDiagram.coordinateSystem.getYByXT(tdDiagram.width, T);
            newLine.setAttribute('id','newLine');
            newLine.setAttribute('x0',0);
            newLine.setAttribute('y0',tdDiagram.height - y0);
            newLine.setAttribute('x1',tdDiagram.width);
            newLine.setAttribute('y1',tdDiagram.height - y1);
            newLine.setAttribute("stroke-width","1")
            newLine.setAttribute("stroke", "red");
            newGroup.appendChild(newLine);
            tdGroup.appendChild(newGroup);
          }
        
      })
     
    }
```
