### ISSUE TITLE
drawing a moved dryDiabat line stopped at the half of the diagram

### ISSUE THREAD

**Issue by hadjersh97** [chird/meteoJS#64]
Hi Chird,

 hope you're fine, it's me again lol , trying to move 5 sorts of lines ( isobar, isotherm, mixingRatio, dryDiabats, pseudoaDiabats).

i  did isobar, isotherm, mixingRation, dryDiabats. i made them moved following your suggestion of last time and also the code of plot of each sort of line. i did some changes : ( i create the line at a specific position then when clicked the line, i followed the mouse mouvement then when i clicked again the line stoped moving).

for drydiabats line i faced a problem: 

   as shown in the picture while i'm moving the mouse in the xAxis  ( from -40° to 40° ) after that the line (with color blue), will not be drawn (the moved dryDiabat line will stopped in the middle of the diagram).  i know that the cause that there are places in the diagram where temperature is hidden. 

So please, do you have any suggestion of how  can i move the line in the rest of the graph. temperature over 40°.  

![dryDiabat](https://user-images.githubusercontent.com/75619237/177125322-b1e35ebc-9d24-4ba9-8b47-94ba2fefe7eb.png)

**Comment by chird** [comment]
Hi hadjersh97,

It is a SVG thing. I think your issue happens when the mouse pointer leave the SVG graphic (e.g. on the right border with the red line). From this moment on, the SVG graphic will no longer receive a mousemove event. That means you have to solve this in some way. The API cannot do anything about this.

**Comment by hadjersh97** [comment]
hello, 
not sure if understand me well , 
i need to move the drydiabat line along the diagram , so the issue is how to get coordination o draw/move that line for the rest of the diagram( above the blue line) for temperatures that is over 40° .
so the question is : is there a way to get coordination (x, y) of a point in the svg without passing temperature since there is issue to get it by mousemove.
or i can just draw the line once then just move it using svg methods yes? .
Thanks in advance.
