### ISSUE TITLE
Add the posibility to obtain parcel indexes

### ISSUE THREAD

**Issue by masterfabela** [chird/meteoJS#76]
There is any way to get this values after display the sounding?

![image](https://user-images.githubusercontent.com/13069345/222423418-4636f7c2-15fe-422d-9c98-c5557121e8f1.png)

![image](https://user-images.githubusercontent.com/13069345/222423862-d7cf375f-d1b2-4db4-a869-a0fe8174b22f.png)

![image](https://user-images.githubusercontent.com/13069345/222424167-3b1654fc-7ab6-49d0-a088-0599350fffbc.png)

Thanks a lot for your attention

**Comment by chird** [comment]
Hi masterfabela,
Do I understand you correctly that you would like to have the values calculated? Then I must refer you to other places. The library only handles the rendering, you have to calculate the values yourself. However, you can still set the properties after constructing.
PS: The names are identical to those in the [SHARPpy](https://github.com/sharppy/SHARPpy) project. There you will find the corresponding algorithms or even programmes for the calculation.
