### ISSUE TITLE
[Question] What is the green line, and how it's calculated?

### ISSUE THREAD

**Issue by github0013** [chird/meteoJS#77]
https://chird.github.io/meteoJS/examples/thermodynamicdiagram-parcellift.html

![Screenshot 2023-03-14 at 11 07 23](https://user-images.githubusercontent.com/809378/224873872-a0c9fe5e-c17d-4202-ab6c-5b51bcee829c.png)

- RED -> temperature
- BLUE -> dew point
- GREEN -> ???

**Comment by chird** [comment]
It is the [wet-bulb temperature](https://en.wikipedia.org/wiki/Wet-bulb_temperature). It's calculated with the `wetbulbTempByTempAndDewpointAndPres` function in the [meteojs/calc](https://github.com/chird/meteoJS/blob/master/src/meteoJS/calc.js) module. For example, it is used to estimate the snowfall limit.
